### PR TITLE
Update to Gatsby 5

### PR DESCRIPTION
**Pull request by wotnak**

### CODE REVIEW

**Comment by mstenta** [comment]
Thanks @wotnak!!! Amazing work!

I did a quick side-by-side click through comparison of the current farmOS.org and the Netlify deploy preview for this PR and this looks really good IMO. No major issues, everything seems to be functionally consistent. There are some minor style differences (@wotnak mentioned this in chat: "might not be 1:1 when it comes to styles because of the required material ui updates, but generally it is updated and seems to work"), but it looks fine to me. There's no need to be pixel perfect with this IMO. :-)

I haven't reviewed the code changes myself, and would like to get some more Gatsby-experienced eyes on it too... but in general this LGTM!

**Comment by paul121** [comment]
Welp currently farmOS.org is not building due to the old Node.js v12 (as noted by @wotnak here: https://github.com/farmOS/farmOS/pull/697#issuecomment-1625685758)

As I understand the `netlify.toml` added via this PR would solve the issue.. so what do we think, is this ready to go?

**Review by paul121 — CHANGES_REQUESTED** [review]
I'm noticing one issue with the mobile/reactivity in the deploy preview. There are widths when both the left and right navs are visible and either make the page off-center or only show half the nav. On the current site these navs disappear at these widths

Screenshot from 2023-07-07 14-08-35
Screenshot from 2023-07-07 14-09-14

**Comment by paul121** [comment]
Aha, it appears that the `<Hidden>` elements in MUI have been deprecated. Pushing a commit to fix this. https://mui.com/material-ui/migration/v5-component-changes/#hidden

**Comment by paul121** [comment]
Ah, also the lg breakpoint size changed between MUI v4 1280px to v5 1200px.

**Review by paul121 — APPROVED** [review]
Okay I think I've fixed the reactive issue. Would appreciate a quick review @jgaehring re: the Gatsby 5 changes!

**Review by jgaehring — APPROVED** [review]
Finally pulled @wotnak's changes, along w/ @paul121's commit to replace the `<Hidden/>` component, and got it running on my local. LGTM!

> Welp currently farmOS.org is not building due to the old Node.js v12 (as noted by @wotnak here: [farmOS/farmOS#697 (comment)](https://github.com/farmOS/farmOS/pull/697#issuecomment-1625685758))
> 
> As I understand the `netlify.toml` added via this PR would solve the issue.. so what do we think, is this ready to go?

I noticed this, too, when I first tried to run it and had to upgrade my local version of Node. Bumped it up to v. 20 (via [`nvm`](https://github.com/nvm-sh/nvm), which is a great utility just fyi) and it worked fine. And yes, the `netlify.toml` should resolve it, and if it doesn't the build will just abort so no risk trying it.

**Comment by jgaehring** [comment]
Want I should merge these changes, @mstenta?

**Comment by mstenta** [comment]
> Want I should merge these changes, @mstenta?

Go for it! Thanks @wotnak @paul121 @jgaehring!

**Comment by jgaehring** [comment]
Alright, all looks good on the production build and farmos.org looks just fine. Here are the build logs:
https://app.netlify.com/sites/gracious-brattain-bdd606/deploys/64ab139041173d0008d09a8a

**Pull request merged**
