### PR TITLE
Fix /guide/assets/* redirects.

### PR DESCRIPTION
**Pull request by mstenta**
See https://github.com/farmOS/farmOS.org/pull/53 for more context.

### CODE REVIEW

**Comment by mstenta** [comment]
Huzzah! That works! Thanks for the suggestion @jgaehring!

**Comment by jgaehring** [comment]
Oh great, LGTM, does that cover all the necessary routes?

**Comment by mstenta** [comment]
I think so. I suppose Google will let us know if other 404s appear.

I'll go ahead and merge and we can wait and see. Thanks again @jgaehring. :-)

**Comment by jgaehring** [comment]
Awesome, thanks Mike!

**Pull request merged**
