### PR TITLE
Blog

### PR DESCRIPTION
**Pull request by jgaehring**
This and #48 should fulfill the implementation requirements for the first deliverable of the [Work Proposal to support community content on farmos.org](https://farmos.discourse.group/t/work-proposal-support-for-community-content-on-farmos-org/1265), which is being funded by the farmOS Open Collective. This PR should also generate a preview deployment on Netlify (the second deliverable), which is sourcing a test repository at [jgaehring/farmOS-community-blog](https://github.com/jgaehring/farmOS-community-blog) (the third deliverable), so that the full feature set can be viewed and tested.

It probably doesn't make sense to merge and deploy this, however, until there is some content ready to be published.

### CODE REVIEW

**Comment by mstenta** [comment]
This looks GREAT @jgaehring!!!

Can we include the year and month in the URLs that are generated? eg: `/blog/2022/06/another-test/` Or is that just controlled by the directory structure of the blog markdown files in the source repo?

I also wonder if we could go with `/posts/...` instead of `/blog/...`? Just personal preference - what do others think? (And again maybe this is just a decision about how we structure the directories in the source repo?)

Lastly, does this support tags/categories yet? Or is that a next step? In the forum you mentioned that simply allowing for categories is "fairly easy":

> In a technical sense, we could fairly easily create a category property in Front matter, we would just need to decide how to present those separate categories in the navigation and other UI elements.

https://farmos.discourse.group/t/work-proposal-support-for-community-content-on-farmos-org/1265/3

I think it would be great to at least start with the ability to categorize posts, and maybe just display them under the date/author line. Using them in navigation and other UI could be a next step...

LOVE to see this come together! And I can't wait to contribute blog posts!! :heart_eyes:

**Comment by jgaehring** [comment]
Thanks, @mstenta! I just drafted up some more detailed notes [on the forum](https://farmos.discourse.group/t/work-proposal-support-for-community-content-on-farmos-org/1265/12), but I can address a few of your points here.

> Can we include the year and month in the URLs that are generated? eg: `/blog/2022/06/another-test/` Or is that just controlled by the directory structure of the blog markdown files in the source repo?

Yes and yes. I've opted for parsimony wherever I can, so the URL can be determined either by the directory structure, which can be as flat or nested as desired, or by the `slug` frontmatter if one is provided. Although I realize it would be nice to combine those in some way, so you could use the file path and the slug together, just replacing the last path segment with the slug. But I also assumed a pretty flat directory structure to start, until a clearer need emerges to organize it more strictly. I suppose we could also introduce permalinks somehow, based on a more deterministic naming convention. Personally, I prefer URL's that are short and descriptive, but perhaps that could be varied depending on the specific category, or determined by whoever elects to take ownership of the content repository (or repositories).

> I also wonder if we could go with `/posts/...` instead of `/blog/...`? Just personal preference - what do others think? (And again maybe this is just a decision about how we structure the directories in the source repo?)

Yea, I almost did this, actually, and I mentioned this on the last dev call too. Ultimately, I'm wary of being too committed to anything early on, until we have a larger corpus of posts, but all we need to do is change the `baseURI` in [`site-data.js`](https://github.com/jgaehring/farmOS.org/blob/bebc68bec6b5184140a382eca9f195eeaefa659b/site-data.js#L64).

> Lastly, does this support tags/categories yet? Or is that a next step?

Not yet, but it is easy to add. I detailed just how that can be done over [on the forum](https://farmos.discourse.group/t/work-proposal-support-for-community-content-on-farmos-org/1265/12#deliverable-1-implementation-1), but again, I'm trying not to put the cart before the horse, because even once we have our first post that's ready to publish, a category of one is really no category at all. Better to put energy into content creation, imo, at least for now.

**Comment by mstenta** [comment]
Update: we moved @jgaehring's repo to the farmOS org: https://github.com/farmOS/farmOS-community-blog

And merged @symbioquine's first post: https://github.com/farmOS/farmOS-community-blog/pull/1

Next step is to test this again and it!

I'm also creating a few next step followup issues:

- https://github.com/farmOS/farmOS.org/issues/25
- https://github.com/farmOS/farmOS.org/issues/52
- https://github.com/farmOS/farmOS.org/issues/55

**Comment by jgaehring** [comment]
@mstenta, I just added you as a reviewer to give the final go-ahead (which you've already done before I can post this, haha) but since @symbioquine's commits from jgaehring/farmOS.org#1 have been added to this one, and your own farmOS/farmOS-community-blog#6 was merged, I will go ahead and merge this one.

As we discussed in Element, right now blog posts will only be displayed on the main index page, and in simple reverse chronological order, rather than being added to the navigation menu. This should suffice until there is enough content to require more robust filtering and/or search features.

**Pull request merged**
