### PR TITLE
Add link to demo site.

### PR DESCRIPTION
**Pull request by paul121**
A simple first pass at #43

### CODE REVIEW

**Comment by jgaehring** [comment]
Awesome, this looks great!

Is there any thing else you wanted to do with it? Otherwise, let's merge it!

**Comment by mstenta** [comment]
Super cool! LGTM!

Side thought: I wonder if https://farmos-demo.rootedsolutions.io/ should emphasize somewhere that the demo only lasts for 24 hours and there isn't any easy way to get it out (yet)... I worry about new users who see this on farmOS.org, start a demo, and start entering tons of their data without understanding that it's temporary. There are so many for-profit services similar to this that are essentially funnels to get customers to pay for the service. This is NOT that, but that may be a subconscious expectation in the minds of some newcomers.

**Comment by paul121** [comment]
> Side thought: I wonder if https://farmos-demo.rootedsolutions.io/ should emphasize somewhere that the demo only lasts for 24 hours and there isn't any easy way to get it out (yet)... 

Good idea. It does display this message after you've created a demo, but never before that point. Attaching screenshot of what is displayed now:

Screenshot from 2022-04-13 14-31-16

Maybe we should add/modify:

> This farmOS demo will persist for **12 hours**. After this time **all data will be lost.** farmOS provides features for exporting data; however, the entire database cannot be exported from the demo environment.

Ideas on how/where to include this information on the homepage?

**Comment by paul121** [comment]
> Is there any thing else you wanted to do with it?

Oh @jgaehring, nope, just wanted to toss something up and get feedback! Learned some react + mui in the process of styling the button - but not my strong suit  :-)

**Pull request merged**
