### PR TITLE
Allow overriding content source repos and their branches using env variables

### PR DESCRIPTION
**Pull request by wotnak**
By default, everything works the same.
If any of the following env variables is set, its value replaces the default content repo url or branch set in the site-data.js.
```
FARMOS_REPO
FARMOS_REPO_BRANCH
FARMOS_JS_REPO
FARMOS_JS_REPO_BRANCH
FARMOS_PY_REPO
FARMOS_PY_REPO_BRANCH
BLOG_REPO
BLOG_REPO_BRANCH
```
This should allow exploring setting up netlify deploy previews for https://github.com/farmOS/farmOS-community-blog repo as discussed in https://github.com/farmOS/farmOS-community-blog/issues/5#issuecomment-1312123030.

### CODE REVIEW

**Comment by wotnak** [comment]
Hmm, it looks like the site is deployed using older nodejs version than what I tested this changes on, which doesn't support `??` nullish coalescing operator.

**Comment by wotnak** [comment]
Also related to this. I've done some [initial work](https://github.com/wotnak/farmOS-community-blog/pull/1) on configuring deploy previews on pull requests for farmOS-community-blog repo. After this pr is merged I'll work on finishing it.

**Review by paul121 — APPROVED** [review]
This is great!

**Review by mstenta — APPROVED** [review]

**Comment by jgaehring** [comment]
Doing a little cleanup on my local git after #79 and realized we can probably delete the branches `source/farmOS` and `source/farmOS-community-blog`, b/c the changes here in #68 obviate the need for them any longer. Does that sound right to you, @mstenta and @wotnak, and shall I go ahead and delete them here on the remote origin?

**Comment by wotnak** [comment]
Should be ok to remove them. farmOS-community-blog has now netlify deploy previews configured directly on the pull requests, and for docs in the main farmOS repo we can probably create a similar deploy preview configuration if needed.

**Comment by jgaehring** [comment]
Awesome, thanks! I'll do so now.

> and for docs in the main farmOS repo we can probably create a similar deploy preview configuration if needed.

Yea, I figure the various source repos can adapt a config similar to farmOS/farmOS-community-blog#13 if and when a preview build is desired for any of those. I may open an issue in farmOS.js for that now, just to have a reference to these two PR's for whenever I may be looking to do so in the future.

**Pull request merged**
