### PR TITLE
Maintainer bios

### PR DESCRIPTION
**Pull request by jgaehring**
Figured I'd start this PR while I was at it, to address #30. I basically just adapted [the bio on my website](https://jgaehring.com/about).

@mstenta and @paul121, want to add your bios as well?

I'd like to tweak the layout a bit once we're done, too.

### CODE REVIEW

**Comment by mstenta** [comment]
Thanks for getting this ball rolling @jgaehring! I updated mine as well. :smile:

We should also invite @symbioquine to add one, if he wants! He is a maintainer of farmOS-map, after all.

**Comment by jgaehring** [comment]
> We should also invite @symbioquine to add one, if he wants! He is a maintainer of farmOS-map, after all.

Totally! I actually wondered that the other day b/c you are still the only maintainer listed in the README.

**Comment by jgaehring** [comment]
Oh and @mstenta check the url on your Twitter href.

**Comment by symbioquine** [comment]
Thanks @mstenta / @jgaehring ! I'll try to get something written up and make a follow-up PR. No need to block this one on me :)

**Comment by mstenta** [comment]
> you are still the only maintainer listed in the README.

Guess we need another PR! :smile: 

> Oh and @mstenta check the url on your Twitter href.

Whoops! I was just trying to give you some extra promotion @jgaehring :rofl: 

I'll force push the correct link... one sec... thanks for the heads up!

**Comment by jgaehring** [comment]
Ok, just wanted to move these changes forward so merged. @paul121 and @symbioquine, feel free to add your updates separately!

**Pull request merged**
